# Generated by binpac_quickstart

refine flow {{ name|upper }}_Flow += {
	function proc_{{ name|lower }}_message(msg: {{ name|upper }}_PDU): bool
		%{
		BifEvent::generate_{{ name|lower }}_event(connection()->bro_analyzer(), connection()->bro_analyzer()->Conn());
		return true;
		%}
};

refine typeattr {{ name|upper }}_PDU += &let {
	proc: bool = $context.flow.proc_{{ name|lower }}_message(this);
};
